### ISSUE TITLE
Staff user in archivist group can add and remove super user permissions.

### ISSUE THREAD

**Issue by whikloj** [danloveg/NCTR-Bagit-Record-Transfer#17]
Playing around with adding an "Administration" link to the header and realized that my `testuser` who is `staff` and in the `archivist` group gets the change user permission. There seems to be no limit on this permission so this user can see/edit the my `admin` super-user.

I was trying to see how one might rectify this, but it is outside my limited knowledge so I pass the issue along and look forward to learning how you would adjust permissions for this.

My expectation is that a non-superuser cannot give or remove the super-user permission from any user.

**Comment by danloveg** [comment]
I wrote the code to display an Admin link in the header earlier today, [this is the commit I'm referring to](https://github.com/danloveg/NCTR-Bagit-Record-Transfer/commit/5db8339918201e1c593503476657296694be5189).

I can add a check to the user save method to only allow a superuser to change the superuser status on another user. I won't get around to this until after the weekend, though.

**Comment by whikloj** [comment]
I'm ok if you take the whole weekend off. 😀

**Comment by danloveg** [comment]
I made it so that if you're not a superuser, you can't edit a superuser account. As a staff user, you can still see the super users, but can't take any action that changes the account.
