### ISSUE TITLE
Typing Date Makes Estimated Date Checkbox Disappear

### ISSUE THREAD

**Issue by danloveg** [danloveg/NCTR-Bagit-Record-Transfer#19]
On Step 4 of the transfer form (Record Description), if you type a full date out in the Earliest date or Latest date fields, the estimated date checkbox disappears. You can make it re-appear by clicking away from the input and clicking the input again.

The fix may be as simple as refreshing the checkbox when a date is selected.

**Comment by whikloj** [comment]
I'll have a look at this one, I had noticed it happened as well.
