### ISSUE TITLE
Rights Form is Too Open

### ISSUE THREAD

**Issue by danloveg** [danloveg/NCTR-Bagit-Record-Transfer#20]
The form to fill out the rights for the transfer is too open for interpretation, and may be confusing for people who are not familiar with copyright and other types of rights.

A dropdown for the rights type may be more appropriate than an open-text field. We may want to provide an "Other" option if someone would like to enter rights in an open-text field of a type we are not familiar with or have overlooked.

**Comment by whikloj** [comment]
I'll give this one a try, I like the idea of some form of fixed taxonomy of rights to start with where the rights name and description are pre-defined but the notes field allows the user to spell out any specifics.

**Comment by danloveg** [comment]
That sounds good. So then the `RightsForm.rights_statement_type` should be changed to a `forms.ChoiceField`. It might also make sense to show another field (initially hidden) if the user selects "Other," the same way if someone selects "Other" in the province/state field.

If you go this route, note that the ID of the rights statement type input follows this format:

`id_rights-<id number>-rights_statement_type`

Where `<id_number>` is any number from 0 upwards.

This is due to the form being a form set, which makes it so you can submit multiple of the same form. Not sure if jQuery has a way to add an event listener to an element with a generic ID, but if so that would make that task a lot easier.

**Comment by whikloj** [comment]
So how does one hide a form field initially? It appears that Django only supports an `attr` on the actual Text widget, so I can hide the widget. I could also override the Field type to add a `hidden` attribute, but both of these seem like overkill. So am I missing something?

**Comment by whikloj** [comment]
Ok, I have the javascript working to get the "Other" textbox (currently titled Custom Rights description) to appear when a specific grouping has "Other" as the option.

![Screen Shot 2021-05-12 at 3 06 54 PM](https://user-images.githubusercontent.com/2857697/118037620-b79a9f80-b333-11eb-9a0f-c796ed652adc.png)

But now I am doing form validation and it appears that if there are multiple fields (ie `rights-0-rights_statement_type` and `rights-1-rights_statement_type`) then only the first value is saved when running `cleaned_data = super().clean()` and it saves it as `rights_statement_type`.

This makes sense as those are the fields defined for Django, but clearly I am missing a Django-ism to get it to see multiple fields or I need a way to return all the values and then re-populate the form on a form error.

**Comment by danloveg** [comment]
You only need to define the logic required to clean _one_ `RightsForm`. If any one `RightsForm` is invalid, the user will not be able to go to the next step. Since the `RightsForm` is declared as a `formset`, you don't need to write logic to check every form, you only need define the validation logic once and the formset applies that logic to each form in the set. If you want to see where the formset is declared, look at `urls.py`.

The `views.TransferFormWizard` manages every step in the transfer form. When every step of the form has been completed and cleaned correctly, each cleaned form from every rights form that was submitted can be accessed like this in the `TransferFormWizard`:

```python
cleaned_data = self.get_all_cleaned_data()
rights_forms = cleaned_data['formset-rights']
```

Then, if you wanted to access each `rights_statement_type`, you could do this:

```python
for form in rights_forms:
    statement_type = form['rights_statement_type']
    # Use the statement type ...
```

You shouldn't need to access each cleaned form like this in the wizard, though, writing the validation logic in `RightsForm.clean` should be sufficient.
