### ISSUE TITLE
Functions Called by Job May Log to Different File

### ISSUE THREAD

**Issue by danloveg** [danloveg/NCTR-Bagit-Record-Transfer#25]
When a job (in `jobs.py`) calls a function outside of itself, that function may write logs to a different file. For example, when the `bag_user_metadata_and_files` job is called, it logs to the `rq.worker` log file, but when `create_bag` is called from that function, the logs are written to the file associated with `recordtransfer`. This creates a blank space in the RQ worker log where we expect to see messages related to the bag's creation (what happened?) but don't

One simple way to change this behaviour would be to have an optional `logger` parameter for functions that know they might be called by jobs. If the logger is not None, use that to log messages, otherwise, use the default logger.

**Comment by whikloj** [comment]
I can work this one.
